CREATE TABLE [dbo].[Song]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Title] NVARCHAR(50) NOT NULL, 
    [CdId] INT NOT NULL, 
    CONSTRAINT [FK_Song_ToCd] FOREIGN KEY (CdId) REFERENCES Cd(Id)
)
